// @vitest-environment node
import { describe, it, expect, vi, beforeEach } from 'vitest';
import express from 'express';
import request from 'supertest';
import cookieParser from 'cookie-parser';
import { createTestApp, createAuthenticatedRequest, mockLogError, mockSaveFile, mockCreateNotification } from '../../test/helpers/server';
import { globalErrorHandler } from '../../middleware/error';

/**
 * Integration Tests - CRUD Generator Routes
 *
 * Tests the CRUD routes generated by createCrudRoutes for all 13 tables.
 * Uses audit-plans as the primary example, then verifies the pattern
 * works consistently for other tables.
 */

// Mock BaseService
const mockBaseService = {
  findAll: vi.fn(),
  findById: vi.fn(),
  create: vi.fn(),
  update: vi.fn(),
  delete: vi.fn(),
};

// Mock AuthService
const mockAuthService = {
  logAudit: vi.fn().mockResolvedValue(undefined),
};

// Mock AuditPlanService
const mockAuditPlanService = {
  create: vi.fn(),
  update: vi.fn(),
};

// Mock RiskService
const mockRiskService = {
  create: vi.fn(),
  update: vi.fn(),
};

// Mock NotificationService (imported dynamically in crudGenerator)
const mockNotificationService = {
  getUserIdByName: vi.fn().mockResolvedValue('owner-user-id'),
  getAdminIds: vi.fn().mockResolvedValue(['admin-1', 'admin-2']),
};

vi.mock('../../services/BaseService', () => ({
  BaseService: {
    findAll: (...args: any[]) => mockBaseService.findAll(...args),
    findById: (...args: any[]) => mockBaseService.findById(...args),
    create: (...args: any[]) => mockBaseService.create(...args),
    update: (...args: any[]) => mockBaseService.update(...args),
    delete: (...args: any[]) => mockBaseService.delete(...args),
  },
}));

vi.mock('../../services/AuthService', () => ({
  AuthService: {
    logAudit: (...args: any[]) => mockAuthService.logAudit(...args),
  },
}));

vi.mock('../../services/AuditPlanService', () => ({
  AuditPlanService: {
    create: (...args: any[]) => mockAuditPlanService.create(...args),
    update: (...args: any[]) => mockAuditPlanService.update(...args),
  },
}));

vi.mock('../../services/RiskService', () => ({
  RiskService: {
    create: (...args: any[]) => mockRiskService.create(...args),
    update: (...args: any[]) => mockRiskService.update(...args),
  },
}));

vi.mock('../../services/NotificationService', () => ({
  NotificationService: {
    getUserIdByName: (...args: any[]) => mockNotificationService.getUserIdByName(...args),
    getAdminIds: (...args: any[]) => mockNotificationService.getAdminIds(...args),
  },
}));

vi.mock('fs', () => ({
  default: { unlink: vi.fn((path, cb) => cb(null)) },
  unlink: vi.fn((path, cb) => cb(null)),
}));

// Import createCrudRoutes after mocks are set up
import { createCrudRoutes } from '../../utils/crudGenerator';

function createCrudTestApp(options?: { role?: string; authenticate?: boolean }) {
  const { app, authenticate, checkPermission } = createTestApp({
    role: options?.role || 'Admin',
    authenticate: options?.authenticate !== false,
  });

  const logError = mockLogError();
  const createNotification = mockCreateNotification();
  const saveFile = mockSaveFile();
  const db = {}; // Not used directly since BaseService is mocked

  const crudRouter = createCrudRoutes(db, authenticate, checkPermission, logError, createNotification, saveFile);
  app.use('/api', crudRouter);
  app.use(globalErrorHandler);

  return { app, createNotification, logError, saveFile };
}

describe('CRUD Generator Integration Tests', () => {
  let app: express.Application;
  let createNotification: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    vi.clearAllMocks();
    const testApp = createCrudTestApp();
    app = testApp.app;
    createNotification = testApp.createNotification;
  });

  // ─── GET /audit-plans (List) ─────────────────────────────────────────────

  describe('GET /api/audit-plans (List)', () => {
    it('should return paginated data with pagination metadata', async () => {
      mockBaseService.findAll.mockResolvedValue({
        data: [
          { id: 1, plan_code: 'IA-PL-24-001', title: 'خطة تدقيق' },
          { id: 2, plan_code: 'IA-PL-24-002', title: 'خطة تدقيق ثانية' },
        ],
        pagination: { page: 1, pageSize: 50, total: 2, totalPages: 1, hasNext: false, hasPrev: false },
      });

      const req = createAuthenticatedRequest(app);
      const res = await req.get('/api/audit-plans');

      expect(res.status).toBe(200);
      expect(res.body.data).toHaveLength(2);
      expect(res.body.pagination).toEqual({
        page: 1,
        pageSize: 50,
        total: 2,
        totalPages: 1,
        hasNext: false,
        hasPrev: false,
      });
    });

    it('should pass search query parameter to BaseService.findAll', async () => {
      mockBaseService.findAll.mockResolvedValue({
        data: [],
        pagination: { page: 1, pageSize: 50, total: 0, totalPages: 0, hasNext: false, hasPrev: false },
      });

      const req = createAuthenticatedRequest(app);
      await req.get('/api/audit-plans?search=financial');

      expect(mockBaseService.findAll).toHaveBeenCalledWith(
        'audit_plans',
        expect.objectContaining({
          where: expect.objectContaining({ search: 'financial' }),
        })
      );
    });

    it('should return 401 without authentication token', async () => {
      const res = await request(app).get('/api/audit-plans');

      expect(res.status).toBe(401);
    });

    it('should require View permission for the module', async () => {
      // Create app with non-Admin role where checkPermission denies access
      const { app: restrictedApp } = createCrudTestApp({ role: 'Viewer' });

      // The default checkPermission in createTestApp allows non-Admin through,
      // so we create a custom app with stricter permission checking
      const { app: customApp, authenticate: auth } = createTestApp({ role: 'Viewer' });
      const strictCheckPermission = (module: string, action: string) => {
        return (req: any, res: any, next: any) => {
          if (req.user?.role === 'Admin') return next();
          // Deny non-Admin users for this test
          return res.status(403).json({ error: `Forbidden: requires ${action} permission on ${module}` });
        };
      };
      const crudRouter = createCrudRoutes({}, auth, strictCheckPermission, vi.fn(), vi.fn(), vi.fn());
      customApp.use('/api', crudRouter);
      customApp.use(globalErrorHandler);

      const req = createAuthenticatedRequest(customApp);
      const res = await req.get('/api/audit-plans');

      expect(res.status).toBe(403);
    });
  });

  // ─── GET /audit-plans/:id (Get by ID) ────────────────────────────────────

  describe('GET /api/audit-plans/:id (Get by ID)', () => {
    it('should return the record when found', async () => {
      mockBaseService.findById.mockResolvedValue({
        id: 'plan-1',
        plan_code: 'IA-PL-24-001',
        title: 'خطة تدقيق مالي',
        department: 'Internal Audit',
        status: 'Planned',
      });

      const req = createAuthenticatedRequest(app);
      const res = await req.get('/api/audit-plans/plan-1');

      expect(res.status).toBe(200);
      expect(res.body.id).toBe('plan-1');
      expect(res.body.plan_code).toBe('IA-PL-24-001');
    });

    it('should return 404 when record does not exist', async () => {
      const { NotFoundError } = await import('../../utils/errors');
      mockBaseService.findById.mockRejectedValue(new NotFoundError('audit_plans record not found'));

      const req = createAuthenticatedRequest(app);
      const res = await req.get('/api/audit-plans/nonexistent-id');

      expect(res.status).toBe(404);
    });
  });

  // ─── POST /audit-plans (Create) ──────────────────────────────────────────

  describe('POST /api/audit-plans (Create)', () => {
    it('should create a record with valid data and return it', async () => {
      mockAuditPlanService.create.mockResolvedValue({
        id: 'new-plan-1',
        plan_code: 'IA-PL-24-001',
        title: 'خطة تدقيق جديدة',
        department: 'Internal Audit',
        type: 'Financial',
      });

      const req = createAuthenticatedRequest(app);
      const res = await req.post('/api/audit-plans').send({
        title: 'خطة تدقيق جديدة',
        department: 'Internal Audit',
        type: 'Financial',
        risk_rating: 'High',
        planned_start_date: '2024-01-01',
        planned_end_date: '2024-03-31',
      });

      expect(res.status).toBe(200);
      expect(res.body.id).toBe('new-plan-1');
      expect(res.body.plan_code).toBe('IA-PL-24-001');
    });

    it('should generate auto-code via AuditPlanService.create', async () => {
      mockAuditPlanService.create.mockResolvedValue({
        id: 'new-plan-2',
        plan_code: 'IA-PL-24-002',
        title: 'خطة أخرى',
      });

      const req = createAuthenticatedRequest(app);
      await req.post('/api/audit-plans').send({
        title: 'خطة أخرى',
        department: 'Internal Audit',
        type: 'Operational',
      });

      // AuditPlanService.create is called (which handles code generation internally)
      expect(mockAuditPlanService.create).toHaveBeenCalledWith(
        'audit_plans',
        expect.objectContaining({ title: 'خطة أخرى' })
      );
    });

    it('should log audit trail after creation', async () => {
      mockAuditPlanService.create.mockResolvedValue({ id: 'plan-x', title: 'Test' });

      const req = createAuthenticatedRequest(app);
      await req.post('/api/audit-plans').send({ title: 'Test', department: 'IT' });

      expect(mockAuthService.logAudit).toHaveBeenCalledWith(
        'testuser',
        'Created audit_plans',
        'audit-plans',
        expect.any(String)
      );
    });

    it('should send notification after creation', async () => {
      mockAuditPlanService.create.mockResolvedValue({ id: 'plan-y', title: 'Notify Test' });

      const req = createAuthenticatedRequest(app);
      await req.post('/api/audit-plans').send({ title: 'Notify Test', department: 'Audit' });

      expect(createNotification).toHaveBeenCalled();
    });

    it('should apply field whitelisting (mass assignment prevention)', async () => {
      mockAuditPlanService.create.mockResolvedValue({ id: 'plan-z', title: 'Safe' });

      const req = createAuthenticatedRequest(app);
      await req.post('/api/audit-plans').send({
        title: 'Safe',
        department: 'IT',
        // These fields should be stripped (not in allowed fields)
        malicious_field: 'hacked',
        is_admin: true,
        role: 'Admin',
      });

      // The body passed to create should NOT contain the malicious fields
      expect(mockAuditPlanService.create).toHaveBeenCalledWith(
        'audit_plans',
        expect.not.objectContaining({
          malicious_field: 'hacked',
          is_admin: true,
          role: 'Admin',
        })
      );
    });

    it('should require Create permission', async () => {
      const { app: customApp, authenticate: auth } = createTestApp({ role: 'Viewer' });
      const strictCheckPermission = (module: string, action: string) => {
        return (req: any, res: any, next: any) => {
          if (req.user?.role === 'Admin') return next();
          return res.status(403).json({ error: `Forbidden: requires ${action} permission on ${module}` });
        };
      };
      const crudRouter = createCrudRoutes({}, auth, strictCheckPermission, vi.fn(), vi.fn(), vi.fn());
      customApp.use('/api', crudRouter);
      customApp.use(globalErrorHandler);

      const req = createAuthenticatedRequest(customApp);
      const res = await req.post('/api/audit-plans').send({ title: 'Test' });

      expect(res.status).toBe(403);
    });
  });

  // ─── PUT /audit-plans/:id (Update) ───────────────────────────────────────

  describe('PUT /api/audit-plans/:id (Update)', () => {
    it('should update a record with valid data', async () => {
      mockAuditPlanService.update.mockResolvedValue({
        id: 'plan-1',
        title: 'خطة محدثة',
        status: 'In Progress',
      });

      const req = createAuthenticatedRequest(app);
      const res = await req.put('/api/audit-plans/plan-1').send({
        title: 'خطة محدثة',
        status: 'In Progress',
      });

      expect(res.status).toBe(200);
      expect(res.body.title).toBe('خطة محدثة');
    });

    it('should prevent modification of immutable fields (plan_code)', async () => {
      mockAuditPlanService.update.mockResolvedValue({ id: 'plan-1', title: 'Updated' });

      const req = createAuthenticatedRequest(app);
      await req.put('/api/audit-plans/plan-1').send({
        title: 'Updated',
        plan_code: 'HACKED-CODE', // plan_code is in allowed fields for the whitelist
      });

      // plan_code IS in the whitelist for audit_plans, but BaseService.update
      // removes immutable fields internally. The route passes it through whitelist.
      // The actual immutability is enforced by BaseService.update
      expect(mockAuditPlanService.update).toHaveBeenCalledWith(
        'audit_plans',
        'plan-1',
        expect.objectContaining({ title: 'Updated' })
      );
    });

    it('should require Edit permission', async () => {
      const { app: customApp, authenticate: auth } = createTestApp({ role: 'Viewer' });
      const strictCheckPermission = (module: string, action: string) => {
        return (req: any, res: any, next: any) => {
          if (req.user?.role === 'Admin') return next();
          return res.status(403).json({ error: `Forbidden: requires ${action} permission on ${module}` });
        };
      };
      const crudRouter = createCrudRoutes({}, auth, strictCheckPermission, vi.fn(), vi.fn(), vi.fn());
      customApp.use('/api', crudRouter);
      customApp.use(globalErrorHandler);

      const req = createAuthenticatedRequest(customApp);
      const res = await req.put('/api/audit-plans/plan-1').send({ title: 'Test' });

      expect(res.status).toBe(403);
    });
  });

  // ─── DELETE /audit-plans/:id (Delete) ─────────────────────────────────────

  describe('DELETE /api/audit-plans/:id (Delete)', () => {
    it('should delete a record and return success', async () => {
      mockBaseService.delete.mockResolvedValue(true);

      const req = createAuthenticatedRequest(app);
      const res = await req.delete('/api/audit-plans/plan-1');

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(mockBaseService.delete).toHaveBeenCalledWith('audit_plans', 'plan-1');
    });

    it('should log audit trail after deletion', async () => {
      mockBaseService.delete.mockResolvedValue(true);

      const req = createAuthenticatedRequest(app);
      await req.delete('/api/audit-plans/plan-1');

      expect(mockAuthService.logAudit).toHaveBeenCalledWith(
        'testuser',
        'Deleted audit_plans ID: plan-1',
        'audit-plans',
        expect.any(String)
      );
    });

    it('should require Delete permission', async () => {
      const { app: customApp, authenticate: auth } = createTestApp({ role: 'Viewer' });
      const strictCheckPermission = (module: string, action: string) => {
        return (req: any, res: any, next: any) => {
          if (req.user?.role === 'Admin') return next();
          return res.status(403).json({ error: `Forbidden: requires ${action} permission on ${module}` });
        };
      };
      const crudRouter = createCrudRoutes({}, auth, strictCheckPermission, vi.fn(), vi.fn(), vi.fn());
      customApp.use('/api', crudRouter);
      customApp.use(globalErrorHandler);

      const req = createAuthenticatedRequest(customApp);
      const res = await req.delete('/api/audit-plans/plan-1');

      expect(res.status).toBe(403);
    });
  });

  // ─── Permission Checks ───────────────────────────────────────────────────

  describe('Permission Checks', () => {
    it('should return 403 when user lacks the required permission for the module', async () => {
      const { app: customApp, authenticate: auth } = createTestApp({ role: 'Staff' });
      const strictCheckPermission = (module: string, action: string) => {
        return (req: any, res: any, next: any) => {
          if (req.user?.role === 'Admin') return next();
          return res.status(403).json({
            error: `Forbidden: requires ${action} permission on ${module}`,
          });
        };
      };
      const crudRouter = createCrudRoutes({}, auth, strictCheckPermission, vi.fn(), vi.fn(), vi.fn());
      customApp.use('/api', crudRouter);
      customApp.use(globalErrorHandler);

      const req = createAuthenticatedRequest(customApp);

      // Test all CRUD operations are denied
      const getRes = await req.get('/api/audit-plans');
      expect(getRes.status).toBe(403);

      const postRes = await req.post('/api/audit-plans').send({ title: 'Test' });
      expect(postRes.status).toBe(403);

      const putRes = await req.put('/api/audit-plans/1').send({ title: 'Test' });
      expect(putRes.status).toBe(403);

      const deleteRes = await req.delete('/api/audit-plans/1');
      expect(deleteRes.status).toBe(403);
    });
  });

  // ─── Other Tables (Pattern Verification) ─────────────────────────────────

  describe('Other Tables - Pattern Verification', () => {
    it('GET /api/risk-register should use RiskService for create', async () => {
      mockRiskService.create.mockResolvedValue({
        id: 'risk-1',
        risk_id: 'RR-24-001',
        description: 'مخاطر تشغيلية',
        owner: 'مدير القسم',
      });

      const req = createAuthenticatedRequest(app);
      const res = await req.post('/api/risk-register').send({
        description: 'مخاطر تشغيلية',
        owner: 'مدير القسم',
        type: 'Operational',
        likelihood: 'Medium',
        impact: 'High',
      });

      expect(res.status).toBe(200);
      expect(mockRiskService.create).toHaveBeenCalledWith(
        'risk_register',
        expect.objectContaining({ description: 'مخاطر تشغيلية' })
      );
    });

    it('GET /api/audit-tasks should return 404 (excluded from CRUD generator, handled by custom routes)', async () => {
      const req = createAuthenticatedRequest(app);
      const res = await req.get('/api/audit-tasks');

      // audit-tasks is excluded from CRUD generator (CRUD_EXCLUDED_ROUTES)
      // and handled by dedicated custom route module instead
      expect(res.status).toBe(404);
    });

    it('POST /api/audit-tasks should return 404 (excluded from CRUD generator, handled by custom routes)', async () => {
      const testApp = createCrudTestApp();
      const req = createAuthenticatedRequest(testApp.app);
      const res = await req.post('/api/audit-tasks').send({
        title: 'مهمة جديدة',
        plan_id: 'plan-1',
        assigned_to: 'user-assigned',
        audit_type: 'Financial',
      });

      // audit-tasks is excluded from CRUD generator (CRUD_EXCLUDED_ROUTES)
      // Notifications for audit-tasks are handled by the custom route module
      expect(res.status).toBe(404);
    });

    it('GET /api/recommendations should return 404 (excluded from CRUD generator, handled by custom routes)', async () => {
      const req = createAuthenticatedRequest(app);
      const res = await req.get('/api/recommendations');

      // recommendations is excluded from CRUD generator (CRUD_EXCLUDED_ROUTES)
      // and handled by dedicated custom route module instead
      expect(res.status).toBe(404);
    });

    it('DELETE /api/fraud-log/:id should work', async () => {
      mockBaseService.delete.mockResolvedValue(true);

      const req = createAuthenticatedRequest(app);
      const res = await req.delete('/api/fraud-log/fraud-1');

      expect(res.status).toBe(200);
      expect(res.body.success).toBe(true);
      expect(mockBaseService.delete).toHaveBeenCalledWith('fraud_log', 'fraud-1');
    });

    it('GET /api/compliance-items should work', async () => {
      mockBaseService.findAll.mockResolvedValue({
        data: [{ id: 1, ref_number: 'CMP-24-001', title: 'تعليمات' }],
        pagination: { page: 1, pageSize: 50, total: 1, totalPages: 1, hasNext: false, hasPrev: false },
      });

      const req = createAuthenticatedRequest(app);
      const res = await req.get('/api/compliance-items');

      expect(res.status).toBe(200);
      expect(res.body.data).toHaveLength(1);
    });

    it('PUT /api/central-bank-instructions/:id should update', async () => {
      mockBaseService.update.mockResolvedValue({
        id: 'cbi-1',
        title: 'تعليمات محدثة',
        status: 'Active',
      });

      const req = createAuthenticatedRequest(app);
      const res = await req.put('/api/central-bank-instructions/cbi-1').send({
        title: 'تعليمات محدثة',
        status: 'Active',
      });

      expect(res.status).toBe(200);
      expect(res.body.title).toBe('تعليمات محدثة');
    });

    it('POST /api/audit-findings should return 404 (excluded from CRUD generator, handled by custom routes)', async () => {
      const testApp = createCrudTestApp();
      const req = createAuthenticatedRequest(testApp.app);
      const res = await req.post('/api/audit-findings').send({
        audit_id: 'audit-1',
        title: 'ملاحظة جديدة',
        description: 'وصف الملاحظة',
        risk_level: 'High',
        status: 'Open',
      });

      expect(res.status).toBe(404);
    });
  });
});
