/**
 * RECORDED BASELINE — Extra_Shared_Types (FIX-FE-1, criteria 1.1 & 1.6)
 *
 * This file is a frozen, independent snapshot of the 8 Extra_Shared_Types as they
 * exist at the time FIX-FE-1 was specified. It MUST NOT import from `../models`;
 * it is a hand-copied record used purely to detect regressions.
 *
 * The companion `type-equality.ts` performs a compile-time bidirectional equality
 * check between these baseline definitions and the live definitions in
 * `../models.ts`. If any field of an Extra_Shared_Type is deleted, renamed,
 * narrowed, or has its optionality/type changed, the equality check fails the
 * TypeScript build (and the accompanying Vitest suite).
 *
 * DO NOT edit this file to "make the check pass" after a model change. A failing
 * check means a guarded type drifted — reconcile the change with the Backend_Team
 * per FIX-FE-1 governance, or restore the field.
 *
 * The 8 Extra_Shared_Types:
 *   DashboardStats, AuditProgressByType, RiskLevelBreakdown, Role, Permission,
 *   UserSession, JobTitle, UserManagementSettings
 */

// ─── Dashboard Stats ──────────────────────────────────────────────────────────

/** Baseline of `AuditProgressByType`. */
export interface BaselineAuditProgressByType {
  type: string;
  planned: number;
  completed: number;
}

/** Baseline of `RiskLevelBreakdown`. */
export interface BaselineRiskLevelBreakdown {
  level: string;
  count: number;
}

/** Baseline of `DashboardStats`. */
export interface BaselineDashboardStats {
  audits: {
    total: number;
    completed: number;
    progress_by_type: BaselineAuditProgressByType[];
  };
  findings: {
    summary: {
      open: number;
      high_risk_open: number;
    };
  };
  recommendations: {
    open: number;
    overdue: number;
  };
  risks: {
    summary: {
      total: number;
      high: number;
    };
    byLevel?: BaselineRiskLevelBreakdown[];
  };
  correspondence: {
    incoming_total: number;
    outgoing_total: number;
    pending_responses: number;
  };
  compliance: {
    total: number;
  };
  activity: Array<Record<string, unknown>>;
}

// ─── User Management ───────────────────────────────────────────────────────────

/** Baseline of `Role`. */
export interface BaselineRole {
  id: string | number;
  name: string;
  description?: string;
}

/** Baseline of `Permission`. */
export interface BaselinePermission {
  id: string | number;
  module: string;
  action: string;
}

/** Baseline of `UserSession`. */
export interface BaselineUserSession {
  id: string | number;
  user_id: string | number;
  ip_address?: string;
  user_agent?: string;
  created_at?: string;
  expires_at?: string;
}

/** Baseline of `JobTitle`. */
export interface BaselineJobTitle {
  id: string | number;
  name: string;
  name_ar?: string;
  name_en?: string;
}

/** Baseline of `UserManagementSettings`. */
export interface BaselineUserManagementSettings {
  failed_login_threshold?: number;
  inactive_account_threshold_days?: number;
  password_min_length?: number;
  password_require_uppercase?: number;
  password_require_lowercase?: number;
  password_require_numbers?: number;
  password_require_symbols?: number;
  password_expiry_days?: number;
  enforce_single_session?: number;
  session_timeout_minutes?: number;
}
