// @vitest-environment node
import { describe, it, expect, afterEach } from 'vitest';
import fc from 'fast-check';
import fs from 'fs';
import path from 'path';
import os from 'os';
import crypto from 'crypto';
import { KeyStore, KeyPair } from '../utils/keyStore';

/**
 * Generator for JWT_SECRET-like strings: alphanumeric strings
 * of reasonable length (8-64 chars) to simulate real secrets.
 */
const secretArb: fc.Arbitrary<string> = fc
  .array(
    fc.constantFrom(...'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'.split('')),
    { minLength: 8, maxLength: 64 }
  )
  .map((chars) => chars.join(''));

/**
 * Generator for valid PEM-formatted strings.
 * Produces strings with proper BEGIN/END markers and base64-encoded content.
 */
function pemKeyArb(type: string): fc.Arbitrary<string> {
  return fc
    .array(fc.base64String({ minLength: 48, maxLength: 64 }), { minLength: 4, maxLength: 20 })
    .map((lines) => {
      const header = `-----BEGIN ${type}-----`;
      const footer = `-----END ${type}-----`;
      return `${header}\n${lines.join('\n')}\n${footer}\n`;
    });
}

/**
 * Generator for KeyPair objects with valid PEM structure.
 */
const keyPairArb: fc.Arbitrary<KeyPair> = fc.record({
  privateKey: pemKeyArb('RSA PRIVATE KEY'),
  publicKey: pemKeyArb('PUBLIC KEY'),
});

/**
 * Generate a real RSA key pair for testing.
 * We use 1024-bit keys for speed in property tests (still valid PEM).
 */
function generateTestKeyPair(): KeyPair {
  const { privateKey, publicKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 1024,
    publicKeyEncoding: { type: 'spki', format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });
  return { privateKey, publicKey };
}

/**
 * Property Test: RSA key persistence round-trip (Property 10)
 *
 * **Validates: Requirements 6.3**
 *
 * For any valid RSA key pair, persisting it via the KeyStore and then loading
 * it must return an identical key pair (byte-for-byte PEM equality).
 */
describe('Property 10: RSA key persistence round-trip', () => {
  const tempDirs: string[] = [];

  function createTempDir(): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'keystore-pbt10-'));
    tempDirs.push(dir);
    return dir;
  }

  afterEach(() => {
    for (const dir of tempDirs) {
      try {
        fs.rmSync(dir, { recursive: true, force: true });
      } catch {
        // Ignore cleanup errors
      }
    }
    tempDirs.length = 0;
  });

  it('persisting and loading a key pair returns byte-for-byte identical PEM content', async () => {
    await fc.assert(
      fc.asyncProperty(keyPairArb, secretArb, async (keyPair, secret) => {
        const tempDir = createTempDir();
        const store = new KeyStore({ dataDir: tempDir, encryptionSecret: secret });

        await store.save(keyPair);
        const loaded = await store.load();

        expect(loaded).not.toBeNull();
        expect(loaded!.privateKey).toBe(keyPair.privateKey);
        expect(loaded!.publicKey).toBe(keyPair.publicKey);
      }),
      { numRuns: 100 }
    );
  });

  it('round-trip works with real RSA key pairs generated by crypto module', async () => {
    await fc.assert(
      fc.asyncProperty(secretArb, async (secret) => {
        const tempDir = createTempDir();
        const keyPair = generateTestKeyPair();
        const store = new KeyStore({ dataDir: tempDir, encryptionSecret: secret });

        await store.save(keyPair);
        const loaded = await store.load();

        expect(loaded).not.toBeNull();
        expect(loaded!.privateKey).toBe(keyPair.privateKey);
        expect(loaded!.publicKey).toBe(keyPair.publicKey);
      }),
      { numRuns: 10 }
    );
  });

  it('getOrCreate returns persisted keys on subsequent calls (no regeneration)', async () => {
    await fc.assert(
      fc.asyncProperty(secretArb, async (secret) => {
        const tempDir = createTempDir();
        const store = new KeyStore({ dataDir: tempDir, encryptionSecret: secret });

        const first = await store.getOrCreate();

        const store2 = new KeyStore({ dataDir: tempDir, encryptionSecret: secret });
        const second = await store2.load();

        expect(second).not.toBeNull();
        expect(second!.privateKey).toBe(first.privateKey);
        expect(second!.publicKey).toBe(first.publicKey);
      }),
      { numRuns: 10 }
    );
  }, 30000);
});

/**
 * Property Test: RSA keys encrypted at rest (Property 11)
 *
 * **Validates: Requirements 6.5**
 *
 * For any persisted key file on disk, the raw file content must not contain
 * PEM markers (`-----BEGIN`), and decryption with the correct `JWT_SECRET`-derived
 * key must yield valid RSA key material.
 */
describe('Property 11: RSA keys encrypted at rest', () => {
  const testDirs: string[] = [];

  function createTempDir(): string {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'keystore-prop11-'));
    testDirs.push(dir);
    return dir;
  }

  afterEach(() => {
    for (const dir of testDirs) {
      try {
        fs.rmSync(dir, { recursive: true, force: true });
      } catch {
        // Ignore cleanup errors
      }
    }
    testDirs.length = 0;
  });

  it('persisted key file does not contain PEM markers in raw content', async () => {
    await fc.assert(
      fc.asyncProperty(secretArb, async (secret) => {
        const dataDir = createTempDir();
        const keyStore = new KeyStore({ dataDir, encryptionSecret: secret });
        const keys = generateTestKeyPair();

        // Sanity check: the generated keys DO contain PEM markers
        expect(keys.privateKey).toContain('-----BEGIN');
        expect(keys.publicKey).toContain('-----BEGIN');

        // Save keys via KeyStore
        await keyStore.save(keys);

        // Read the raw file content from disk
        const keyFilePath = path.join(dataDir, 'keys', '.rsa_keys.enc');
        expect(fs.existsSync(keyFilePath)).toBe(true);

        const rawContent = fs.readFileSync(keyFilePath, 'utf8');

        // The raw file content must NOT contain PEM markers (proving encryption)
        expect(rawContent).not.toContain('-----BEGIN');
        expect(rawContent).not.toContain('-----END');

        // The raw content must NOT contain the actual private key data
        expect(rawContent).not.toContain(keys.privateKey);
        expect(rawContent).not.toContain(keys.publicKey);
      }),
      { numRuns: 100 }
    );
  });

  it('persisted key file is valid JSON with iv, tag, and data fields', async () => {
    await fc.assert(
      fc.asyncProperty(secretArb, async (secret) => {
        const dataDir = createTempDir();
        const keyStore = new KeyStore({ dataDir, encryptionSecret: secret });
        const keys = generateTestKeyPair();

        await keyStore.save(keys);

        const keyFilePath = path.join(dataDir, 'keys', '.rsa_keys.enc');
        const rawContent = fs.readFileSync(keyFilePath, 'utf8');

        // Must be valid JSON
        const parsed = JSON.parse(rawContent);

        // Must have the expected encrypted payload structure
        expect(parsed).toHaveProperty('iv');
        expect(parsed).toHaveProperty('tag');
        expect(parsed).toHaveProperty('data');

        // All fields must be non-empty strings (base64 encoded)
        expect(typeof parsed.iv).toBe('string');
        expect(parsed.iv.length).toBeGreaterThan(0);
        expect(typeof parsed.tag).toBe('string');
        expect(parsed.tag.length).toBeGreaterThan(0);
        expect(typeof parsed.data).toBe('string');
        expect(parsed.data.length).toBeGreaterThan(0);
      }),
      { numRuns: 100 }
    );
  });

  it('decryption with correct secret yields valid RSA key material', async () => {
    await fc.assert(
      fc.asyncProperty(secretArb, async (secret) => {
        const dataDir = createTempDir();
        const keyStore = new KeyStore({ dataDir, encryptionSecret: secret });
        const keys = generateTestKeyPair();

        await keyStore.save(keys);

        // Load the keys back using the same secret
        const loaded = await keyStore.load();
        expect(loaded).not.toBeNull();

        // Decrypted content must match original PEM keys exactly
        expect(loaded!.privateKey).toBe(keys.privateKey);
        expect(loaded!.publicKey).toBe(keys.publicKey);

        // Verify the loaded keys are valid RSA key material
        expect(loaded!.privateKey).toContain('-----BEGIN PRIVATE KEY-----');
        expect(loaded!.publicKey).toContain('-----BEGIN PUBLIC KEY-----');

        // Verify the keys can be used for crypto operations (sign/verify)
        const testData = 'test-payload';
        const sign = crypto.createSign('SHA256');
        sign.update(testData);
        const signature = sign.sign(loaded!.privateKey, 'base64');

        const verify = crypto.createVerify('SHA256');
        verify.update(testData);
        expect(verify.verify(loaded!.publicKey, signature, 'base64')).toBe(true);
      }),
      { numRuns: 100 }
    );
  });

  it('decryption with wrong secret fails to yield original keys', async () => {
    await fc.assert(
      fc.asyncProperty(secretArb, secretArb, async (secret1, secret2) => {
        // Ensure the two secrets are different
        fc.pre(secret1 !== secret2);

        const dataDir = createTempDir();
        const keyStore1 = new KeyStore({ dataDir, encryptionSecret: secret1 });
        const keyStore2 = new KeyStore({ dataDir, encryptionSecret: secret2 });
        const keys = generateTestKeyPair();

        await keyStore1.save(keys);

        // Attempting to load with a different secret should fail (return null)
        const loaded = await keyStore2.load();
        // KeyStore returns null when decryption fails
        expect(loaded).toBeNull();
      }),
      { numRuns: 100 }
    );
  });
});
