import React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { useTranslation } from 'react-i18next';
import { Button } from '@/components/ui/button';
import { 
  CorrespondenceClassification, 
  SendingMethod 
} from '../../constants';
import api from '../../api/httpClient';
import toast from 'react-hot-toast';
import { Input } from '../../components/ui/Input';
import { Select } from '../../components/ui/Select';
import { FormField } from '../../components/ui/FormField';
import logger from '../../utils/logger';
import { useFileUploadValidation } from '../../hooks/useFileUploadValidation';

const outgoingSchema = z.object({
  letter_date: z.string().min(1, 'Field is required'),
  recipient_entity: z.string().min(1, 'Field is required'),
  subject: z.string().min(1, 'Field is required'),
  classification: z.nativeEnum(CorrespondenceClassification),
  sending_method: z.nativeEnum(SendingMethod),
  attachment_file: z.any().optional(),
});

type OutgoingFormValues = z.infer<typeof outgoingSchema>;

interface OutgoingFormProps {
  language: 'ar' | 'en';
  onSuccess: () => void;
  onCancel: () => void;
}

const OutgoingForm: React.FC<OutgoingFormProps> = ({ language, onSuccess, onCancel }) => {
  const { t } = useTranslation();
  const { validateAndFilter } = useFileUploadValidation({
    allowedExtensions: ['.pdf'],
    allowedMimeTypes: ['application/pdf'],
  });
  
  const {
    register,
    handleSubmit,
    formState: { errors, isSubmitting },
  } = useForm<OutgoingFormValues>({
    resolver: zodResolver(outgoingSchema),
    mode: 'onBlur',
    defaultValues: {
      letter_date: new Date().toISOString().split('T')[0] ?? '',
      classification: CorrespondenceClassification.GENERAL,
      sending_method: SendingMethod.OFFICIAL_MAIL,
    },
  });

  const onSubmit = async (data: OutgoingFormValues) => {
    try {
      const formData = new FormData();
      formData.append('letter_date', data.letter_date);
      formData.append('recipient_entity', data.recipient_entity);
      formData.append('subject', data.subject);
      formData.append('classification', data.classification);
      formData.append('sending_method', data.sending_method);
      
      if (data.attachment_file && data.attachment_file[0]) {
        const validFiles = await validateAndFilter([data.attachment_file[0] as File]);
        if (validFiles.length > 0) {
          formData.append('attachment_file', validFiles[0]!);
        } else {
          return; // Validation failed, toast already shown
        }
      }
      
      await api.post('/correspondence/outgoing', formData);
      onSuccess();
    } catch (error) {
      logger.error("Failed to save outgoing correspondence", error);
      toast.error(t('errorOccurred'));
    }
  };

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <FormField label={t('correspondence.sequenceNumber')} error={errors.letter_date?.message} className="opacity-60 cursor-not-allowed">
          <Input defaultValue={t('correspondence.autoGenerated')} disabled className="bg-[var(--color-bg-soft)] dark:bg-slate-900 border-dashed" />
        </FormField>

        <FormField label={t('correspondence.letterDate')} error={errors.letter_date?.message} required>
          <Input type="date" {...register('letter_date')} />
        </FormField>

        <FormField label={t('correspondence.recipientEntity')} error={errors.recipient_entity?.message} required className="md:col-span-2">
          <Input {...register('recipient_entity')} defaultValue="" placeholder={t('correspondence.recipientEntityPlaceholder')} />
        </FormField>

        <FormField label={t('correspondence.subject')} error={errors.subject?.message} required className="md:col-span-2">
          <Input {...register('subject')} defaultValue="" placeholder={t('correspondence.letterSubjectPlaceholder')} />
        </FormField>

        <FormField label={t('correspondence.classification')} error={errors.classification?.message}>
          <Select {...register('classification')}>
            {Object.values(CorrespondenceClassification).map(cls => (
              <option key={cls} value={cls}>{t(`correspondence.${cls.toLowerCase().replace(/\s+/g, '_')}`)}</option>
            ))}
          </Select>
        </FormField>

        <FormField label={t('correspondence.sendingMethod')} error={errors.sending_method?.message}>
          <Select {...register('sending_method')}>
            {Object.values(SendingMethod).map(method => (
              <option key={method} value={method}>{t(`correspondence.${method.toLowerCase().replace(/\s+/g, '_')}`)}</option>
            ))}
          </Select>
        </FormField>

        <FormField label={t('correspondence.attachmentPdf')} error={errors.attachment_file?.message as string} className="md:col-span-2">
          <Input type="file" accept="application/pdf" {...register('attachment_file')} />
        </FormField>
      </div>

      <div className="flex justify-end gap-6 pt-8 border-t border-[var(--color-border-soft)] dark:border-slate-800">
        <button 
          type="button"
          onClick={onCancel}
          className="px-8 py-3 text-[var(--color-text-muted)] dark:text-[var(--color-text-muted)] font-bold uppercase tracking-widest hover:bg-[var(--color-bg-main)] dark:hover:bg-slate-800 rounded-xl transition-all"
        >
          {t('common.cancel')}
        </button>
        <Button 
          type="submit"
          disabled={isSubmitting}
          className="disabled:opacity-50 flex items-center justify-center gap-2"
        >
          {isSubmitting ? t('correspondence.saving') : t('correspondence.registerLetter')}
        </Button>
      </div>
    </form>
  );
};

export default OutgoingForm;
