/**
 * Property 2: Envelope fidelity
 *
 * **Validates: Requirements 2.1**
 *
 * For ANY successful backend response `{ success: true, data, meta }`:
 *   - `unwrapEnvelope(env)` returns the inner `data` — deep-equal AND
 *     reference-identical (proving nothing is copied, reordered, or rebuilt).
 *   - `readEnvelopeMeta(env)` returns the `meta` block (reference-identical).
 *   - When the same envelope flows through the real `createApiClient`, the value
 *     handed to the caller's Zod schema is deep-equal to `data` with no fields
 *     added, removed, or reordered (verified by key-order-preserving
 *     `JSON.stringify` equality).
 *
 * The property is exercised over arbitrary JSON `data` values (arrays, nested
 * objects, primitives, null) and arbitrary object `meta` blocks generated by
 * fast-check, so fidelity is asserted across the whole success-envelope input
 * space rather than a handful of fixtures.
 */
import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import fc from 'fast-check';
import MockAdapter from 'axios-mock-adapter';
import { z } from 'zod';
import { createApiClient, type ApiClientConfig } from '../../api/client';
import { unwrapEnvelope, readEnvelopeMeta } from '../../api/utils/envelope';

// ─── Generators ────────────────────────────────────────────────────────────────

/** Arbitrary JSON-compatible `data` payload: arrays, nested objects, primitives, null. */
const arbData = fc.jsonValue();

/** Arbitrary object `meta` block (a non-null object, as `readEnvelopeMeta` requires). */
const arbMeta = fc.dictionary(fc.string(), fc.jsonValue());

/** A success envelope wrapping arbitrary `data` and `meta`. */
const arbSuccessEnvelope = fc.record({
  success: fc.constant(true as const),
  data: arbData,
  meta: arbMeta,
});

// ─── Property 2 (helpers) — reference-identical unwrap + meta ───────────────────

describe('Property 2: Envelope fidelity — helpers (Requirement 2.1)', () => {
  it('unwrapEnvelope returns the exact inner data (reference-identical, no reorder) for any success envelope', () => {
    fc.assert(
      fc.property(arbSuccessEnvelope, (envelope) => {
        const unwrapped = unwrapEnvelope(envelope);

        // Reference identity is the strongest proof nothing was copied/rebuilt.
        expect(unwrapped).toBe(envelope.data);
        // Deep-equal — no field added or removed.
        expect(unwrapped).toEqual(envelope.data);
        // Key order preserved exactly.
        expect(JSON.stringify(unwrapped)).toBe(JSON.stringify(envelope.data));
      }),
      { numRuns: 200 }
    );
  });

  it('readEnvelopeMeta returns the exact meta block (reference-identical) for any success envelope', () => {
    fc.assert(
      fc.property(arbSuccessEnvelope, (envelope) => {
        const meta = readEnvelopeMeta(envelope);

        expect(meta).toBe(envelope.meta);
        expect(meta).toEqual(envelope.meta);
      }),
      { numRuns: 200 }
    );
  });
});

// ─── Property 2 (end-to-end through createApiClient) ────────────────────────────

describe('Property 2: Envelope fidelity — through createApiClient (Requirement 2.1)', () => {
  const config: ApiClientConfig = { baseUrl: 'http://localhost:3000/api', timeout: 5000 };

  beforeEach(() => {
    Object.defineProperty(document, 'cookie', {
      writable: true,
      value: 'csrf-token=test-csrf-token-123',
    });
  });

  afterEach(() => {
    vi.restoreAllMocks();
    Object.defineProperty(document, 'cookie', { writable: true, value: '' });
  });

  it('passes a value deep-equal to envelope.data (no fields added/removed/reordered) to the caller schema', async () => {
    await fc.assert(
      fc.asyncProperty(arbData, arbMeta, async (data, meta) => {
        const client = createApiClient(config);
        const mock = new MockAdapter(client.http);
        mock.onGet('/x').reply(200, { success: true, data, meta });

        // A passthrough schema whose `parse` returns its input unchanged, spied
        // to capture exactly what value the client hands to the caller's schema.
        const schema = z.unknown();
        const parseSpy = vi.spyOn(schema, 'parse');

        const result = await client.get('/x', schema);

        // The caller's schema is invoked exactly once with the unwrapped data.
        expect(parseSpy).toHaveBeenCalledTimes(1);
        const valuePassedToSchema = parseSpy.mock.calls[0]?.[0];

        // The value validated by the caller equals `data` with identical key order.
        expect(valuePassedToSchema).toEqual(data);
        expect(JSON.stringify(valuePassedToSchema)).toBe(JSON.stringify(data));

        // The returned (unwrapped) result is the data — never the envelope.
        expect(result).toEqual(data);

        mock.restore();
      }),
      { numRuns: 100 }
    );
  });
});
